# Generated by Django 3.2.7 on 2021-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('security_level', models.CharField(choices=[
                    (1, 'superuser'), (2, 'admin'), (3, 'basic'),
                    (4, 'high level clinician'), (5, 'medium level clinician'),
                    (6, 'low level clinician')], default=3, max_length=50)
                 ),
                ('security_q1', models.CharField(max_length=200)),
                ('security_q2', models.CharField(max_length=200)),
                ('security_q3', models.CharField(max_length=200)),
                ('security_a1', models.CharField(max_length=200)),
                ('security_a2', models.CharField(max_length=200)),
                ('security_a3', models.CharField(max_length=200)),
            ],
        ),
    ]
