# Generated by Django 3.2.7 on 2021-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_level',
            field=models.CharField(choices=[
                (1, 'Superuser'), (2, 'Admin'),
                (3, 'Basic'), (4, 'High level clinician'),
                (5, 'Medium level clinician'),
                (6, 'Low level clinician')],
                default=3, max_length=50),
        ),
    ]
