# Generated by Django 3.2.7 on 2021-09-23 18:07

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateTimeField()),
                ('preexisting_conditions', models.CharField(max_length=700)),
                ('allergies', models.CharField(max_length=700)),
                ('height_ft', models.PositiveIntegerField()),
                ('height_in', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('email', models.CharField(max_length=200)),
                ('phone', phone_field.models.PhoneField(help_text="Patient's preferred phone number", max_length=31)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
